version: "2"

services:
  writeservice-back:
    container_name: writeservice-back
    build: .
    command:  >
      bash -c "cd /app &&
      yarn install && 
      ts-node ./node_modules/.bin/typeorm migration:run && 
      yarn run start"
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    depends_on:
      - writeservice-pgdb
    restart: always
  writeservice-pgdb:
    container_name: writeservice-pgdb
    image: postgres:10.6
    volumes:
      - ./:/app
      - writeservice-pgdb-data:/var/lib/postgresql/
    environment:
      POSTGRES_USER: ws_user
      POSTGRES_PASSWORD: ws_password
      POSTGRES_DB: writeservice
    ports:
      - 54322:5432
    restart: always
  writeservice-service:
    container_name: writeservice-service
    build: .
    command:  >
      bash -c "cd /app && yarn run service"
    volumes:
      - ./:/app
    depends_on:
      - writeservice-back
      - writeservice-pgdb
    restart: always
volumes:
  writeservice-pgdb-data: